export const ROUTES = {
  LOGIN: "/login",
  MANUAL_LOGIN: "/login/manual",
  REGISTER: "/register",

  DESK_OFFICER: "/desk_officer",
  DESK_OFFICER_REGISTER_VICTIM: "/desk_officer/register_victim",
  DESK_OFFICER_VICTIM_FACIAL: "/desk_officer/victim_facial",
  DESK_OFFICER_SESSION: "/desk_officer/session",
  TEST: "/test",

  DSWD: "/dswd",
  DSWD_VAWC_VICTIMS: "/dswd/victims",
  DSWD_VICTIM_DETAIL: "/dswd/victims/:vic_id",
  DSWD_SEARCH_VICTIM: "/dswd/victims/search",
  DSWD_SOCIAL_WORKERS: "/dswd/social-workers",
  DSWD_CASE_RECORDS: "/dswd/case-records",
  DSWD_SERVICES: "/dswd/services",
  DSWD_NOTIFICATION: "/dswd/notification",
  DSWD_FILE_MAINTENANCE: "/dswd/file-maintenance",

  SOCIAL_WORKER: "/social_worker",
  SOCIAL_WORKER_DASHBOARD: "dashboard",
  SOCIAL_WORKER_CASE_RECORDS: "case-records",
  SOCIAL_WORKER_SESSIONS: "sessions",
  SOCIAL_WORKER_SERVICES: "services",
  SOCIAL_WORKER_VICTIMS: "victims",
  SOCIAL_WORKER_VICTIM_DETAIL: "victims/:vic_id",
  SOCIAL_WORKER_SEARCH_FACIAL: "victims/search-facial",
};
