# Generated by Django 5.2.3 on 2025-08-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VictimSurvivor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=50)),
                ('is_sogie', models.CharField(max_length=50)),
                ('specific_sogie', models.CharField(blank=True, max_length=50)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=100)),
                ('is_minor', models.BooleanField(editable=False)),
                ('guardian_first_name', models.CharField(max_length=100)),
                ('guardian_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_last_name', models.CharField(max_length=100)),
                ('guardian_contact', models.CharField(max_length=20)),
            ],
        ),
    ]
