# Generated by Django 5.2.3 on 2025-08-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VictimSurvivor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=50)),
                ('is_sogie', models.CharField(max_length=50)),
                ('specific_sogie', models.CharField(blank=True, max_length=50)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=100)),
                ('civil_status', models.CharField(max_length=100)),
                ('educational_attainment', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('specific_nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=100, null=True)),
                ('main_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('migratory_status', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('specific_religion', models.CharField(blank=True, max_length=100, null=True)),
                ('is_displaced', models.BooleanField(default=False)),
                ('pwd', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=20)),
                ('is_minor', models.BooleanField(editable=False)),
                ('guardian_first_name', models.CharField(max_length=100)),
                ('guardian_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_last_name', models.CharField(max_length=100)),
                ('guardian_contact', models.CharField(max_length=20)),
                ('child_category', models.CharField(blank=True, max_length=100, null=True)),
                ('employment_status', models.CharField(max_length=50)),
                ('employed_type', models.CharField(blank=True, max_length=100, null=True)),
                ('employer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('employer_address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
