# Generated by Django 5.2.3 on 2025-08-06 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_officer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informantName', models.CharField(blank=True, max_length=100, null=True)),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='desk_officer.victimsurvivor')),
            ],
        ),
    ]
