# Generated by Django 5.2.3 on 2025-09-04 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desk_officer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VictimSurvivor',
        ),
    ]
