# Generated by Django 5.2.3 on 2025-08-10 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desk_officer', '0002_incidentdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IncidentDetail',
        ),
    ]
