export const VICTIM_FIELDS = [
  "vic_first_name",
  "vic_middle_name",
  "vic_last_name",
  "vic_extension",
  "vic_alias",
  "vic_sex",
  "vic_birth_date",
  "vic_birth_place",

  "vic_civil_status",
  "vic_religion",
  "vic_educational_attainment",
  "vic_last_school_attended",
  "vic_last_school_address",
  "vic_occupation",
  "vic_income",
  "vic_skills",
  "vic_current_address",
  "vic_contact_number",
  "vic_provincial_address",
];

export const INCIDENT_KEYS = [
  "violence_type",
  "violence_subtype",
  "incident_description",
  "incident_date",
  "incident_time",
  "incident_location",
  "type_of_place",
  "is_via_electronic_means",
  "electronic_means",
  "is_conflict_area",
  "conflict_area",
  "is_calamity_area",
];

export const PERP_KEYS = [
  "per_first_name",
  "per_middle_name",
  "per_last_name",
  "per_extension",
  "per_alias",
  "per_sex",
  "per_birth_date",
  "per_birth_place",
  "per_religion",
  "per_victim_relationship",
  "per_educational_attainment",
  "per_contact_number",
  "per_occupation",
];

export const CONTACT_PERSON_FIELDS = [
  "cont_fname",
  "cont_mname",
  "cont_lname",
  "cont_ext",
  "cont_sex",
  "cont_birth_date",
  "cont_birth_place",
  "cont_civil_status",
  "cont_victim_relationship",
  "cont_contact_number",
];
