# Generated by Django 5.2.3 on 2025-08-16 10:33

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Perpetrator',
            fields=[
                ('perp_id', models.AutoField(primary_key=True, serialize=False)),
                ('per_first_name', models.CharField(max_length=100)),
                ('per_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('per_last_name', models.CharField(max_length=100)),
                ('per_sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('per_birth_date', models.DateField(blank=True, null=True)),
                ('per_birth_place', models.CharField(blank=True, max_length=255, null=True)),
                ('per_guardian_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('per_guardian_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('per_guardian_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('per_guardian_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('per_guardian_child_category', models.CharField(blank=True, max_length=50, null=True)),
                ('per_nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('per_nationality_other', models.CharField(blank=True, max_length=100, null=True)),
                ('per_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('per_religion', models.CharField(blank=True, max_length=50, null=True)),
                ('per_religion_other', models.CharField(blank=True, max_length=100, null=True)),
                ('per_relationship_category', models.CharField(blank=True, max_length=50, null=True)),
                ('per_relationship_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('per_actor_type', models.CharField(blank=True, max_length=50, null=True)),
                ('per_state_actor_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('per_security_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('per_non_state_actor_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Official',
            fields=[
                ('of_id', models.AutoField(primary_key=True, serialize=False)),
                ('of_fname', models.CharField(max_length=50)),
                ('of_lname', models.CharField(max_length=50)),
                ('of_m_initial', models.CharField(blank=True, max_length=50, null=True)),
                ('of_suffix', models.CharField(blank=True, max_length=50, null=True)),
                ('of_sex', models.CharField(blank=True, max_length=1, null=True)),
                ('of_dob', models.DateField(blank=True, null=True)),
                ('of_pob', models.CharField(blank=True, max_length=255, null=True)),
                ('of_address', models.TextField(blank=True, null=True)),
                ('of_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('of_role', models.CharField(blank=True, choices=[('VAWDesk', 'VAWDesk'), ('Social Worker', 'Social Worker'), ('DSWD', 'DSWD')], max_length=50, null=True)),
                ('of_brgy_assigned', models.CharField(blank=True, max_length=100, null=True)),
                ('of_specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('of_photo', models.ImageField(upload_to='photos/')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shared_model.account')),
            ],
        ),
        migrations.CreateModel(
            name='OfficialFaceSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='face_samples/')),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_samples', to='shared_model.official')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentInformation',
            fields=[
                ('incident_id', models.AutoField(primary_key=True, serialize=False)),
                ('incident_description', models.TextField()),
                ('incident_date', models.DateField()),
                ('incident_time', models.TimeField()),
                ('incident_location', models.CharField(blank=True, max_length=255, null=True)),
                ('type_of_place', models.CharField(choices=[('Conjugal Home', 'Conjugal Home'), ('Evacutaion Area', 'Evacutaion Area'), ('Evacuation Area', 'Evacuation Area'), ('Malls/Hotels', 'Malls/Hotels'), ("Perpetrator's Home", "Perpetrator's Home"), ('Public Utility Vehicle', 'Public Utility Vehicle'), ("Victim's Home", "Victim's Home"), ('Workplace', 'Workplace')], max_length=50)),
                ('is_via_electronic_means', models.BooleanField(default=False)),
                ('electronic_means', models.CharField(blank=True, max_length=50, null=True)),
                ('is_conflict_area', models.BooleanField(default=False)),
                ('conflict_area', models.CharField(blank=True, choices=[('Insurgency', 'Insurgency'), ('Violent Extremism', 'Violent Extremism'), ('Tribal Violence', 'Tribal Violence'), ('Political Violence', 'Political Violence'), ('Rido', 'Rido'), ('Others', 'Others')], max_length=50, null=True)),
                ('is_calamity_area', models.BooleanField(default=False)),
                ('of_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handled_incidents', to='shared_model.official')),
                ('perp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_incidents', to='shared_model.perpetrator')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sess_id', models.AutoField(primary_key=True, serialize=False)),
                ('sess_date_today', models.DateField(blank=True, null=True)),
                ('sess_type', models.TextField(blank=True, null=True)),
                ('sess_notes', models.TextField(blank=True, null=True)),
                ('sess_created_at', models.DateField(blank=True, null=True)),
                ('sess_updated_at', models.DateField(blank=True, null=True)),
                ('sess_next_sched', models.DateField(blank=True, null=True)),
                ('sess_description', models.TextField(blank=True, null=True)),
                ('sess_status', models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Done', 'Done')], default='Pending', max_length=20)),
                ('incident_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='shared_model.incidentinformation')),
                ('of_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions_handled', to='shared_model.official')),
            ],
        ),
        migrations.CreateModel(
            name='Session_Changelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_changed_timestamp', models.DateTimeField()),
                ('sc_field_changed', models.CharField(max_length=100)),
                ('sc_old_value', models.TextField()),
                ('sc_new_value', models.TextField()),
                ('sc_reason_for_update', models.TextField()),
                ('sess_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changelogs', to='shared_model.session')),
            ],
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('vic_id', models.AutoField(primary_key=True, serialize=False)),
                ('vic_last_name', models.CharField(max_length=100)),
                ('vic_first_name', models.CharField(max_length=100)),
                ('vic_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vic_extension', models.CharField(blank=True, max_length=10, null=True)),
                ('vic_sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('vic_is_SOGIE', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Does not want to identify', 'Does not want to identify')], default='No', max_length=50)),
                ('vic_birth_date', models.DateField(blank=True, null=True)),
                ('vic_birth_place', models.CharField(blank=True, max_length=100, null=True)),
                ('vic_civil_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed'), ('SEPARATED', 'Separated'), ('DIVORCED', 'Divorced')], default='SINGLE', max_length=50)),
                ('vic_educational_attainment', models.CharField(choices=[('No Formal Education', 'No Formal Education'), ('Elementary Level/Graduate', 'Elementary Level/Graduate'), ('Junior High School Level/Graduate', 'Junior High School Level/Graduate'), ('Senior High School Level/Graduate', 'Senior High School Level/Graduate'), ('Technical/Vocational', 'Technical/Vocational'), ('College Level/Graduate', 'College Level/Graduate'), ('Post graduate', 'Post graduate')], default='No Formal Education', max_length=50)),
                ('vic_nationality', models.CharField(choices=[('Filipino', 'Filipino'), ('Others', 'Others')], default='Filipino', max_length=50)),
                ('vic_ethnicity', models.CharField(blank=True, max_length=50, null=True)),
                ('vic_main_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('vic_monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vic_employment_status', models.CharField(choices=[('Employed', 'Employed'), ('Self-employed', 'Self-employed'), ('Unemployed', 'Unemployed'), ('Informal Sector', 'Informal Sector'), ('Not Applicable', 'Not Applicable')], default='Not Applicable', max_length=50)),
                ('vic_migratory_status', models.CharField(choices=[('Current OFW', 'Current OFW'), ('Former/Returning OFW', 'Former/Returning OFW'), ('Seeking employment abroad', 'Seeking employment abroad'), ('Not Applicable', 'Not Applicable')], default='Not Applicable', max_length=50)),
                ('vic_religion', models.CharField(choices=[('Roman Catholic', 'Roman Catholic'), ('Islam', 'Islam'), ('Evangelicals', 'Evangelicals'), ('Protestant', 'Protestant'), ('Iglesia ni Cristo', 'Iglesia ni Cristo'), ('Others', 'Others')], default='Roman Catholic', max_length=50)),
                ('vic_is_displaced', models.BooleanField(default=False)),
                ('vic_PWD_type', models.CharField(choices=[('None', 'None'), ('Deaf or Hard of Hearing', 'Deaf or Hard of Hearing'), ('Intellectual Disability', 'Intellectual Disability'), ('Learning DIsability', 'Learning DIsability'), ('Mental Disability', 'Menatl Disability'), ('Orthopedic Disability', 'Orthopedic Disability'), ('Physical Disability', 'Physical Disability'), ('Psychological Disability', 'Psychological Disability'), ('Speech and Language Disability', 'Speech and Language Disability'), ('Visual Disability', 'Visual Disability')], default='None', max_length=50)),
                ('vic_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('vic_photo', models.ImageField(blank=True, null=True, upload_to='victim_photos/')),
                ('vic_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared_model.account')),
            ],
        ),
        migrations.AddField(
            model_name='incidentinformation',
            name='vic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='shared_model.victim'),
        ),
        migrations.CreateModel(
            name='CaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handling_org', models.CharField(blank=True, max_length=255)),
                ('office_address', models.CharField(blank=True, max_length=255)),
                ('report_type', models.CharField(blank=True, max_length=255)),
                ('informant_name', models.CharField(blank=True, max_length=255)),
                ('informant_relationship', models.CharField(blank=True, max_length=255)),
                ('informant_contact', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('victim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_report', to='shared_model.victim')),
            ],
        ),
        migrations.CreateModel(
            name='VictimFaceSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='victim_face_samples/')),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_samples', to='shared_model.victim')),
            ],
        ),
    ]
