# Generated by Django 5.2.3 on 2025-07-28 12:26

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=1)),
                ('dob', models.DateField()),
                ('pob', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=50)),
                ('brgy_assigned', models.CharField(max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shared_model.account')),
            ],
        ),
    ]
