# Generated by Django 5.2.3 on 2025-09-05 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_model', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='official',
            name='account',
        ),
        migrations.AlterField(
            model_name='victim',
            name='vic_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='official',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='official', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='official',
            name='of_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
