# Generated by Django 5.2.3 on 2025-09-05 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='official',
            name='of_address',
        ),
        migrations.RemoveField(
            model_name='official',
            name='of_brgy_assigned',
        ),
        migrations.RemoveField(
            model_name='perpetrator',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='perpetrator',
            name='per_actor_type',
        ),
        migrations.RemoveField(
            model_name='perpetrator',
            name='per_guardian_child_category',
        ),
        migrations.RemoveField(
            model_name='perpetrator',
            name='per_guardian_contact',
        ),
        migrations.RemoveField(
            model_name='perpetrator',
            name='per_guardian_first_name',
        ),
        migrations.RemoveField(
            model_name='perpetrator',
            name='per_guardian_last_name',
        ),
        migrations.RemoveField(
            model_name='perpetrator',
            name='per_guardian_middle_name',
        ),
        migrations.RemoveField(
            model_name='perpetrator',
            name='per_nationality_other',
        ),
        migrations.RemoveField(
            model_name='perpetrator',
            name='per_non_state_actor_detail',
        ),
        migrations.RemoveField(
            model_name='perpetrator',
            name='per_relationship_detail',
        ),
        migrations.RemoveField(
            model_name='perpetrator',
            name='per_religion_other',
        ),
        migrations.RemoveField(
            model_name='perpetrator',
            name='per_security_branch',
        ),
        migrations.RemoveField(
            model_name='perpetrator',
            name='per_state_actor_detail',
        ),
        migrations.AddField(
            model_name='perpetrator',
            name='per_contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='official',
            name='assigned_barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_officials', to='shared_model.barangay'),
        ),
        migrations.AddField(
            model_name='victim',
            name='barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='victims', to='shared_model.barangay'),
        ),
        migrations.AddField(
            model_name='victim',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='victims', to='shared_model.city'),
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='shared_model.city')),
            ],
        ),
        migrations.AddField(
            model_name='barangay',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barangays', to='shared_model.municipality'),
        ),
        migrations.AddField(
            model_name='victim',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='victims', to='shared_model.municipality'),
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitios', to='shared_model.barangay')),
            ],
        ),
        migrations.AddField(
            model_name='official',
            name='sitio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='officials', to='shared_model.sitio'),
        ),
        migrations.AddField(
            model_name='victim',
            name='sitio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='victims', to='shared_model.sitio'),
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='shared_model.sitio')),
            ],
        ),
        migrations.AddField(
            model_name='official',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officials', to='shared_model.street'),
        ),
        migrations.AddField(
            model_name='victim',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='victims', to='shared_model.street'),
        ),
        migrations.AddConstraint(
            model_name='municipality',
            constraint=models.UniqueConstraint(fields=('city', 'name'), name='unique_municipality_per_city'),
        ),
        migrations.AddConstraint(
            model_name='barangay',
            constraint=models.UniqueConstraint(fields=('municipality', 'name'), name='unique_barangay_per_municipality'),
        ),
        migrations.AddConstraint(
            model_name='sitio',
            constraint=models.UniqueConstraint(fields=('barangay', 'name'), name='unique_sitio_per_barangay'),
        ),
        migrations.AddConstraint(
            model_name='street',
            constraint=models.UniqueConstraint(fields=('sitio', 'name'), name='unique_street_per_sitio'),
        ),
    ]
