# Generated by Django 5.2.3 on 2025-08-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_model', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='sess_notes',
            new_name='sess_financial_note',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='sess_type',
            new_name='sess_mental_note',
        ),
        migrations.RemoveField(
            model_name='session',
            name='sess_created_at',
        ),
        migrations.AddField(
            model_name='session',
            name='sess_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='sess_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='sess_physical_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='sess_date_today',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
