# Generated by Django 5.2.3 on 2025-07-28 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared_model.account'),
        ),
        migrations.AlterField(
            model_name='official',
            name='brgy_assigned',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='official',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='official',
            name='pob',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='official',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='official',
            name='sex',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
