# Generated by Django 5.2.3 on 2025-08-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='of_role',
            field=models.CharField(choices=[('DSWD', 'DSWD'), ('VAWDesk', 'VAWDesk'), ('Social Worker', 'Social Worker')], default=False, max_length=50),
        ),
    ]
