# Generated by Django 5.2.3 on 2025-08-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casereport',
            name='handling_org',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='casereport',
            name='informant_contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='casereport',
            name='informant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='casereport',
            name='informant_relationship',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='casereport',
            name='office_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='casereport',
            name='report_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='official',
            name='of_role',
            field=models.CharField(blank=True, choices=[('DSWD', 'DSWD'), ('VAWDesk', 'VAWDesk'), ('Social Worker', 'Social Worker')], max_length=50, null=True),
        ),
    ]
