# Generated by Django 5.2.3 on 2025-09-06 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_model', '0002_barangay_city_remove_official_of_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casereport',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='casereport',
            name='informant_contact',
        ),
        migrations.RemoveField(
            model_name='casereport',
            name='informant_name',
        ),
        migrations.RemoveField(
            model_name='casereport',
            name='informant_relationship',
        ),
    ]
