# Generated by Django 5.2.3 on 2025-07-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_model', '0002_alter_official_account_alter_official_brgy_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='official',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
