# Generated by Django 5.2.3 on 2025-08-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_model', '0002_alter_casereport_handling_org_and_more'), #0002_alter_official_of_role
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='of_role',
            field=models.CharField(choices=[('Social Worker', 'Social Worker'), ('VAWDesk', 'VAWDesk'), ('DSWD', 'DSWD')], default=False, max_length=50),
        ),
    ]
