# Generated by Django 5.2.3 on 2025-08-11 11:09

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_model', '0002_alter_official_of_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='vic_photo',
            field=models.ImageField(blank=True, null=True, upload_to='victim_photos/'),
        ),
        migrations.AlterField(
            model_name='official',
            name='of_role',
            field=models.CharField(choices=[('DSWD', 'DSWD'), ('Social Worker', 'Social Worker'), ('VAWDesk', 'VAWDesk')], default=False, max_length=50),
        ),
        migrations.CreateModel(
            name='VictimFaceSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='victim_face_samples/')),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_samples', to='shared_model.victim')),
            ],
        ),
    ]
