# Generated by Django 5.2.3 on 2025-08-13 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_model', '0003_alter_official_of_role'),
        ('shared_model', '0003_victim_vic_photo_alter_official_of_role_and_more'),
    ]

    operations = [
    ]
