# Generated by Django 5.2.3 on 2025-07-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_model', '0003_alter_official_address_alter_official_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='official',
            name='name',
        ),
        migrations.AddField(
            model_name='official',
            name='fname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='official',
            name='lname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='official',
            name='m_initial',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='official',
            name='suffix',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='official',
            name='role',
            field=models.CharField(choices=[('Social Worker', 'Social Woker'), ('Victim', 'Victim'), ('DSWD', 'DSWD'), ('VAWDesk', 'VAWDesk')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
