# Generated by Django 5.2.3 on 2025-09-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_model', '0003_remove_casereport_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='of_id',
        ),
    ]
