# Generated by Django 5.2.3 on 2025-09-06 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_model', '0004_remove_session_of_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentinformation',
            name='barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='shared_model.barangay'),
        ),
        migrations.AddField(
            model_name='incidentinformation',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='shared_model.city'),
        ),
        migrations.AddField(
            model_name='incidentinformation',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='shared_model.municipality'),
        ),
        migrations.AddField(
            model_name='incidentinformation',
            name='sitio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='shared_model.sitio'),
        ),
        migrations.AddField(
            model_name='incidentinformation',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='shared_model.street'),
        ),
        migrations.AddField(
            model_name='official',
            name='barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='officials', to='shared_model.barangay'),
        ),
        migrations.AddField(
            model_name='official',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='officials', to='shared_model.city'),
        ),
        migrations.AddField(
            model_name='official',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='officials', to='shared_model.municipality'),
        ),
    ]
