# Generated by Django 5.2.3 on 2025-08-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_model', '0004_merge_20250813_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='of_role',
            field=models.CharField(choices=[('VAWDesk', 'VAWDesk'), ('DSWD', 'DSWD'), ('Social Worker', 'Social Worker')], default=False, max_length=50),
        ),
    ]
