# Generated by Django 5.2.3 on 2025-08-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_model', '0005_alter_official_of_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='of_role',
            field=models.CharField(choices=[('DSWD', 'DSWD'), ('Social Worker', 'Social Worker'), ('VAWDesk', 'VAWDesk')], default=False, max_length=50),
        ),
    ]
