# Generated by Django 5.2.3 on 2025-09-06 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_model', '0005_incidentinformation_barangay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='sess_type',
            field=models.CharField(blank=True, choices=[('Counseling', 'Counseling'), ('Mediation', 'Mediation'), ('Interview', 'Interview'), ('Follow-up', 'Follow-up')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incidentinformation',
            name='of_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_incidents', to='shared_model.official'),
        ),
        migrations.AlterField(
            model_name='incidentinformation',
            name='perp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_incidents', to='shared_model.perpetrator'),
        ),
    ]
