# Generated by Django 5.2.3 on 2025-07-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_model', '0005_alter_official_account_alter_official_m_initial_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='official',
            old_name='address',
            new_name='of_address',
        ),
        migrations.RenameField(
            model_name='official',
            old_name='brgy_assigned',
            new_name='of_brgy_assigned',
        ),
        migrations.RenameField(
            model_name='official',
            old_name='contact',
            new_name='of_contact',
        ),
        migrations.RenameField(
            model_name='official',
            old_name='dob',
            new_name='of_dob',
        ),
        migrations.RenameField(
            model_name='official',
            old_name='embedding',
            new_name='of_embedding',
        ),
        migrations.RenameField(
            model_name='official',
            old_name='fname',
            new_name='of_fname',
        ),
        migrations.RenameField(
            model_name='official',
            old_name='lname',
            new_name='of_lname',
        ),
        migrations.RenameField(
            model_name='official',
            old_name='m_initial',
            new_name='of_m_initial',
        ),
        migrations.RenameField(
            model_name='official',
            old_name='photo',
            new_name='of_photo',
        ),
        migrations.RenameField(
            model_name='official',
            old_name='pob',
            new_name='of_pob',
        ),
        migrations.RenameField(
            model_name='official',
            old_name='sex',
            new_name='of_sex',
        ),
        migrations.RenameField(
            model_name='official',
            old_name='specialization',
            new_name='of_specialization',
        ),
        migrations.RenameField(
            model_name='official',
            old_name='suffix',
            new_name='of_suffix',
        ),
        migrations.RemoveField(
            model_name='official',
            name='id',
        ),
        migrations.RemoveField(
            model_name='official',
            name='role',
        ),
        migrations.AddField(
            model_name='official',
            name='of_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='official',
            name='of_role',
            field=models.CharField(choices=[('DSWD', 'DSWD'), ('Social Worker', 'Social Woker'), ('VAWDesk', 'VAWDesk')], default='DSWD', max_length=50),
        ),
    ]
