# Generated by Django 5.2.3 on 2025-07-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_model', '0006_rename_address_official_of_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='of_role',
            field=models.CharField(choices=[('Social Worker', 'Social Woker'), ('VAWDesk', 'VAWDesk'), ('DSWD', 'DSWD')], default='DSWD', max_length=50),
        ),
    ]
