# Generated by Django 5.2.3 on 2025-08-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_model', '0006_alter_official_of_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='of_role',
            field=models.CharField(blank=True, choices=[('VAWDesk', 'VAWDesk'), ('Social Worker', 'Social Worker'), ('DSWD', 'DSWD')], max_length=50, null=True),
        ),
    ]
