# Generated by Django 5.2.3 on 2025-07-31 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_model', '0007_alter_official_of_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='of_role',
            field=models.CharField(choices=[('DSWD', 'DSWD'), ('Social Worker', 'Social Woker'), ('VAWDesk', 'VAWDesk')], default='DSWD', max_length=50),
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('vic_id', models.AutoField(primary_key=True, serialize=False)),
                ('vic_last_name', models.CharField(max_length=100)),
                ('vic_first_name', models.CharField(max_length=100)),
                ('vic_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vic_extension', models.CharField(blank=True, max_length=10, null=True)),
                ('vic_sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('vic_is_SOGIE', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Does not want to identify', 'Does not want to identify')], default='No', max_length=50)),
                ('vic_birth_date', models.DateField(blank=True, null=True)),
                ('vic_birth_place', models.CharField(blank=True, max_length=100, null=True)),
                ('vic_civil_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed'), ('SEPARATED', 'Separated'), ('DIVORCED', 'Divorced')], default='SINGLE', max_length=50)),
                ('vic_educational_attainment', models.CharField(choices=[('No Formal Education', 'No Formal Education'), ('Elementary Level/Graduate', 'Elementary Level/Graduate'), ('Junior High School Level/Graduate', 'Junior High School Level/Graduate'), ('Senior High School Level/Graduate', 'Senior High School Level/Graduate'), ('Technical/Vocational', 'Technical/Vocational'), ('College Level/Graduate', 'College Level/Graduate'), ('Post graduate', 'Post graduate')], default='No Formal Education', max_length=50)),
                ('vic_nationality', models.CharField(choices=[('Filipino', 'Filipino'), ('Others', 'Others')], default='Filipino', max_length=50)),
                ('vic_ethnicity', models.CharField(blank=True, max_length=50, null=True)),
                ('vic_main_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('vic_monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vic_employment_status', models.CharField(choices=[('Employed', 'Employed'), ('Self-employed', 'Self-employed'), ('Unemployed', 'Unemployed'), ('Informal Sector', 'Informal Sector'), ('Not Applicable', 'Not Applicable')], default='Not Applicable', max_length=50)),
                ('vic_migratory_status', models.CharField(choices=[('Current OFW', 'Current OFW'), ('Former/Returning OFW', 'Former/Returning OFW'), ('Seeking employment abroad', 'Seeking employment abroad'), ('Not Applicable', 'Not Applicable')], default='Not Applicable', max_length=50)),
                ('vic_religion', models.CharField(choices=[('Roman Catholic', 'Roman Catholic'), ('Islam', 'Islam'), ('Evangelicals', 'Evangelicals'), ('Protestant', 'Protestant'), ('Iglesia ni Cristo', 'Iglesia ni Cristo'), ('Others', 'Others')], default='Roman Catholic', max_length=50)),
                ('vic_is_displaced', models.BooleanField(default=False)),
                ('vic_PWD_type', models.CharField(choices=[('None', 'None'), ('Deaf or Hard of Hearing', 'Deaf or Hard of Hearing'), ('Intellectual Disability', 'Intellectual Disability'), ('Learning DIsability', 'Learning DIsability'), ('Mental Disability', 'Menatl Disability'), ('Orthopedic Disability', 'Orthopedic Disability'), ('Physical Disability', 'Physical Disability'), ('Psychological Disability', 'Psychological Disability'), ('Speech and Language Disability', 'Speech and Language Disability'), ('Visual Disability', 'Visual Disability')], default='None', max_length=50)),
                ('vic_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('vic_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared_model.account')),
            ],
        ),
        migrations.CreateModel(
            name='Perpetrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_last_name', models.CharField(max_length=100)),
                ('per_first_name', models.CharField(max_length=100)),
                ('per_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('per_sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('per_birth_date', models.DateField()),
                ('per_birth_place', models.CharField(max_length=100)),
                ('per_main_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('per_religion', models.CharField(choices=[('Roman Catholic', 'Roman Catholic'), ('Islam', 'Islam'), ('Evangelicals', 'Evangelicals'), ('Protestant', 'Protestant'), ('Iglesia ni Cristo', 'Iglesia ni Cristo'), ('Others', 'Others')], default='Roman Catholic', max_length=50)),
                ('vic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared_model.victim')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_description', models.TextField()),
                ('incident_date', models.DateField()),
                ('incident_time', models.TimeField()),
                ('incident_location', models.CharField(blank=True, max_length=255, null=True)),
                ('type_of_place', models.CharField(choices=[('Conjugal Home', 'Conjugal Home'), ('Evacutaion Area', 'Evacutaion Area'), ('Malls/Hotels', 'Malls/Hotels'), ("Perpetrator's Home", "Perpetrator's Home"), ('Public Utility Vehicle', 'Public Utility Vehicle'), ("Victim's Home", "Victim's Home"), ('Workplace', 'Workplace')], max_length=50)),
                ('is_via_electronic_means', models.BooleanField(default=False)),
                ('electronic_means', models.CharField(blank=True, max_length=50, null=True)),
                ('is_conflict_area', models.BooleanField(default=False)),
                ('conflict_area', models.CharField(blank=True, choices=[('Insurgency', 'Insurgency'), ('Violent Extremism', 'Violent Extremism'), ('Tribal Violence', 'Tribal Violence'), ('Political Violence', 'Political Violence'), ('Rido', 'Rido'), ('Others', 'Others')], max_length=50, null=True)),
                ('is_calamity_area', models.BooleanField(default=False)),
                ('vic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='shared_model.victim')),
            ],
        ),
    ]
