# Generated by Django 5.2.3 on 2025-08-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_model', '0008_alter_official_of_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='of_role',
            field=models.CharField(choices=[('DSWD', 'DSWD'), ('Social Worker', 'Social Woker'), ('VAWDesk', 'VAWDesk')], default='DSWD', max_length=50),
        ),
    ]
