# Generated by Django 5.2.3 on 2025-08-01 13:55

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_model', '0008_alter_official_of_role_victim_perpetrator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='official',
            name='of_embedding',
        ),
        migrations.AlterField(
            model_name='official',
            name='of_role',
            field=models.CharField(choices=[('VAWDesk', 'VAWDesk'), ('DSWD', 'DSWD'), ('Social Worker', 'Social Worker')], default='DSWD', max_length=50),
        ),
        migrations.CreateModel(
            name='OfficialFaceSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='face_samples/')),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_samples', to='shared_model.official')),
            ],
        ),
    ]
