# Generated by Django 5.2.3 on 2025-08-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_model', '0008_alter_official_of_role_victim_perpetrator_and_more'),
        ('shared_model', '0019_alter_official_of_role'),
    ]

    operations = [
    ]
