# Generated by Django 5.2.3 on 2025-08-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_model', '0020_merge_20250802_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='of_role',
            field=models.CharField(choices=[('DSWD', 'DSWD'), ('VAWDesk', 'VAWDesk'), ('Social Worker', 'Social Woker')], default='DSWD', max_length=50),
        ),
    ]
