# Generated by Django 5.2.3 on 2025-08-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_model', '0023_alter_official_of_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='of_role',
            field=models.CharField(choices=[('VAWDesk', 'VAWDesk'), ('Social Worker', 'Social Woker'), ('DSWD', 'DSWD')], default='DSWD', max_length=50),
        ),
    ]
