# Generated by Django 5.2.3 on 2025-08-05 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_model', '0009_remove_official_of_embedding_alter_official_of_role_and_more'),
        ('shared_model', '0025_alter_official_of_role'),
    ]

    operations = [
    ]
