# Generated by Django 5.2.3 on 2025-07-28 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_worker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
